### ISSUE TITLE
Bugs die ich gefunden habe und die du unbedingt fixen solltest weil ... eh ... darum!

### ISSUE THREAD

**Issue by WoweePaw** [YannickFricke/TwitchUnfollowNotifier#1]
- Fallback für die Channelsprache (default kann auch null sein) ggf. in der Config einstellbar ob deDE oder enUS/enGB etc.
- Nach einiger Zeit können die Follows für länger nicht mehr abgefragt werden weil die API gespammt wird(?). Jedenfalls kommt Statuscode 429 zurück (too many requests). Ggf. den Header auslesen (sofern Twitch einen sendet) wie lange gewartet werden muss bevor man wieder fragen darf.

Ansonsten nicerdicer Stuff. Macht genau das was es soll. ^^

**Comment by YannickFricke** [comment]
Thank you for your feedback!
Gonna fix it tomorrow probably! :)

**Comment by YannickFricke** [comment]
Going to resolve the issues separatly in issue #2 and #3.

Thanks again for your feedback! :)
