### ISSUE TITLE
Improved Check for Unfollows

### ISSUE THREAD

**Issue by WoweePaw** [YannickFricke/TwitchUnfollowNotifier#5]
Möglicherweise wäre es sinnvoll 2-3x zu checken ob die Liste sich verändert bevor er die Nachricht raushaut. Ich hatte gestern das Gefühl das bei Twitch die API spinnt und er einfach meinte das 22 Leute instant unfollowed hätten (was btw. nicht passiert ist) die wurden allerdings alle benachrichtigt. :)

Daher mein Vorschlag ggf. 2-3x zu prüfen ob die Unfollows tatsächlich weiterhin unfollowed sind. 👍 

Ansonsten wie immer vielen Dank für deine Arbeit an diesem kleinen aber feinen Tool. :)

**Comment by YannickFricke** [comment]
@D3thw0lf Danke für die netten Worte! :)

Im Verlauf des Wochenendes sollte das implementiert sein! :)

**Comment by YannickFricke** [comment]
@D3thw0lf 
Wurde mit 17ccc74a536c9d6b8e4783efb07ab1102ffde032 implementiert! :)
Viel Spaß beim Nutzen! :+1:
